import os

env = DefaultEnvironment().Clone()
BIN_DIR = os.environ['BIN_DIR']
LIB_DIR = os.environ['LIB_DIR']

os.path.join(LIB_DIR,"*")

# env.Library(os.path.join(LIB_DIR, 'assets'), ['assets.c']);

# env['LIBS'] = ['assets'] + env['LIBS']
# env['LINKFLAGS'] = env['OS_SUBSYSTEM_WINDOWS'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'demo1'), ['demo1.c'])
