import os
import copy
import platform

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];
TOOLS_NAME = os.environ['TOOLS_NAME'] 

BASE_SOURCES=Glob('*.c') + \
  Glob('*/*.c')

env=DefaultEnvironment().Clone()

OS_NAME = platform.system()
LINKFLAGS = env['LINKFLAGS'];
STATIC_LIBS = ['']
LINK_ALL=''

if OS_NAME == 'Windows':
  if TOOLS_NAME == '' :
    DEPS_LIBS= STATIC_LIBS + ['']
    # LINKFLAGS += ' /DEF:"" '

env.Library(os.path.join(LIB_DIR, 'test_src'), BASE_SOURCES, LIBS=[])